### PR TITLE
Optogenetics Follow Up

### PR DESCRIPTION
**Pull request by pauladkisson**
Implement feedback from Lerner Lab on Optogenetic Conversion

TODOs
- [x] Add info about LED and pulse generator
- [x] add pulse width
- [x] Convert DMS Inhibitory Group 2
- [x] Convert DLS Excitatory files organized by date (instead of treatment group)
- [x]  Convert DMS Excitatory aggregated-only sessions -- asked Lerner Lab --> follow-up PR
- [x] Add missing MSNs
- [x] Assign experimental stage to MSN: Probe Test Habit Training TTL

### CODE REVIEW

**Comment by pauladkisson** [comment]
For the optogenetic light source, the Lerner Lab used 2 devices instead of 1: The [Optogenetics-LED-Dual](https://www.prizmatix.com/Optogenetics/Optogenetics-LED-Dual.aspx) driven by the [OptogeneticsPulserPlus](https://www.prizmatix.com/optogenetics/PulserPlus.htm).  BUT `pynwb.ogen.OptogeneticStimulusSite` only takes 1 device to link with the series.  I added a description that references both devices but it feels a bit hacky.

Curious to get your take @alessandratrapani.

**Comment by alessandratrapani** [comment]
I would put [Optogenetics-LED-Dual](https://www.prizmatix.com/Optogenetics/Optogenetics-LED-Dual.aspx) as the ogen stite device, because this is the actual excitation source. Then I like the solution of linking the other device, that it's just a TTL generator, in the description of [Optogenetics-LED-Dual](https://www.prizmatix.com/Optogenetics/Optogenetics-LED-Dual.aspx).

**Comment by pauladkisson** [comment]
> I would put [Optogenetics-LED-Dual](https://www.prizmatix.com/Optogenetics/Optogenetics-LED-Dual.aspx) as the ogen stite device, because this is the actual excitation source. Then I like the solution of linking the other device, that it's just a TTL generator, in the description of [Optogenetics-LED-Dual](https://www.prizmatix.com/Optogenetics/Optogenetics-LED-Dual.aspx).

Ok, lmk what you think of my new solution.

**Review by alessandratrapani — APPROVED** [review]
OK!

**Pull request merged**
