### PR TITLE
Behavior Interface from MedPC files

### PR DESCRIPTION
**Pull request by pauladkisson**
This PR sets up a behavioral interface for operant box data from medpc text files.

It also takes care of some initial repo set up with convert session and NWB converter.

The medpc text files are first processed by an initial file reader in a dedicated medpc.py file which outputs a dictionary. Then, they are slotted into the appropriate NWB data types in the behavior interface.

There is only one hack that I would like to point out to see if you can find a better solution: the med PC text files include a metadata field for the number of the operant box in which the session occurred. I couldn't find a great place to put this, so I just included it in the description of the behavior processing module.

### CODE REVIEW

**Review by alessandratrapani — APPROVED** [review]
Looks very good! Can you share an example stubbed file?

**Comment by alessandratrapani** [comment]
> There is only one hack that I would like to point out to see if you can find a better solution: the med PC text files include a metadata field for the number of the operant box in which the session occurred. I couldn't find a great place to put this, so I just included it in the description of the behavior processing module.

I think your solution is already good. In my personal experience, the cage number is usually related to the subject; thus, I prefer it to be in the description of the subject. However, this operant box might be common for more than one subject, making it more related to the experimental setup than the subject itself, i.e., your solution is good enough. 
So this could be a guiding principle: if the operant box ID is subject-specific, it should go in the subject description; if not, it's ok to specify it in the description of the behavioral module. What do you think?
@rly is there a consistent way to specify the cage number?

**Comment by pauladkisson** [comment]
> Looks very good! Can you share an example stubbed file?

See drive folder: https://drive.google.com/drive/folders/1I5_OG9KgcCskHRxIs0gHDlLGdOoEDaCM?usp=drive_link

**Comment by pauladkisson** [comment]
> So this could be a guiding principle: if the operant box ID is subject-specific, it should go in the subject description; if not, it's ok to specify it in the description of the behavioral module. What do you think?

Yeah, that seems right to me. The operant box ID is not the same as the Home cage number, end it can change for a single animal.

**Pull request merged**
